version: '3'

services:
  db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=DBPASSWORD
    env_file:
      - db.env

  redis:
    image: redis
    restart: always
    command: redis-server --requirepass REDISPASSWORD

  app:
    image: nextcloud:27-apache
    restart: always
    volumes:
      - ../daten:/var/www/html
    environment:
      - VIRTUAL_HOST=DOMAIN
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=DOMAIN
      - LETSENCRYPT_EMAIL=EMAIL
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD=REDISPASSWORD
    env_file:
      - db.env
    depends_on:
      - db
      - redis
    networks:
      - proxy-tier
      - default

  cron:
    image: nextcloud:27-apache
    restart: always
    volumes:
      - ../daten:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  proxy:
    build: ./proxydockerfile 
    restart: always
    ports:
      - 80:80
      - 443:443
#   environment:
#     - SSL_POLICY=Mozilla-Modern
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - ./proxy/certs:/etc/nginx/certs:ro
      - ./proxy/vhost.d:/etc/nginx/vhost.d
      - ./proxy/html:/usr/share/nginx/html
      - ./proxy/dhparam:/etc/nginx/dhparam
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - ./proxy/certs:/etc/nginx/certs
      - ./proxy/vhost.d:/etc/nginx/vhost.d
      - ./proxy/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

networks:
  proxy-tier:
